"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Download, FileText, Printer } from "lucide-react";

type Value = number | "NOT_APPLICABLE";
type Compared = { baseline: Value; fairDrop: Value; difference: Value; percentageDifference?: Value };
type Report = { summary: { name: string; scenario: string; virtualUsers: number; durationSeconds: number; requestRate: number; concurrency: number; seed: number; createdAt: string | null; startedAt: string | null; completedAt: string | null; baselineRunId: string; fairDropRunId: string }; performance: { traffic: { totalRequests: Compared; requestsPerSecond: Compared }; responses: Record<string, Compared>; latency: Record<string, Compared>; errors: Record<string, Compared> }; queue: Record<string, Compared>; abuse: Record<string, Compared>; allocation: Record<string, Compared>; integrity: Record<string, Compared>; fairness: { baselineNormalRate: { value: number | null; confidenceInterval95: { lower: number; upper: number } | null }; baselineAttackRate: { value: number | null; confidenceInterval95: { lower: number; upper: number } | null }; fairDropNormalRate: { value: number | null; confidenceInterval95: { lower: number; upper: number } | null }; fairDropAttackRate: { value: number | null; confidenceInterval95: { lower: number; upper: number } | null }; normalVsAttackDifference: Compared }; charts: { latency: Record<string, Compared>; allocation: Record<string, Compared>; integrity: Record<string, Compared>; outcomes: Record<string, Compared> } };
type ExperimentOption = { experimentId: string; name: string; status: string };

export default function ReportsPage() {
  const [experiments, setExperiments] = useState<ExperimentOption[]>([]);
  const [selected, setSelected] = useState("");
  const [report, setReport] = useState<Report | null>(null);
  const [state, setState] = useState<"loading" | "empty" | "ready" | "error">("loading");
  useEffect(() => { void (async () => {
    const response = await fetch("/api/admin/experiments", { cache: "no-store" });
    if (!response.ok) { setState("error"); return; }
    const complete = ((await response.json()).experiments as ExperimentOption[]).filter((item) => item.status === "COMPLETED");
    setExperiments(complete);
    if (!complete.length) setState("empty"); else { setSelected(complete[0].experimentId); setState("loading"); }
  })(); }, []);
  useEffect(() => { if (!selected) return; void (async () => {
    setState("loading");
    const response = await fetch(`/api/admin/reports/${selected}`, { cache: "no-store" });
    if (!response.ok) { setState("error"); return; }
    setReport((await response.json()).report); setState("ready");
  })(); }, [selected]);
  function exportCsv() {
    if (!report) return;
    const rows = [["Metric", "Baseline", "FairDrop", "Difference"], ...reportRows(report).map(([label, value]) => [label, String(value.baseline), String(value.fairDrop), String(value.difference)])];
    const blob = new Blob([rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(",")).join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${report.summary.name.replaceAll(/[^a-z0-9]+/gi, "-")}-report.csv`; anchor.click(); URL.revokeObjectURL(url);
  }
  return <div className="mx-auto w-full max-w-7xl space-y-6 p-5 sm:p-7 lg:p-10 print:p-0">
    <div className="flex flex-col justify-between gap-5 border-b border-white/[0.07] pb-6 md:flex-row md:items-end print:hidden"><div><div className="mb-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500"><span>Testing &amp; data</span><span className="text-slate-700">/</span><span className="text-cyan-200">Reports</span></div><h1 className="flex items-center gap-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl"><span className="flex h-11 w-11 items-center justify-center rounded-2xl border border-cyan-300/15 bg-cyan-300/[0.06]"><FileText className="h-5 w-5 text-cyan-200" /></span>Before vs after reports</h1><p className="mt-3 text-sm leading-6 text-slate-400">Compare measured results from completed baseline and FairDrop runs.</p></div><div className="flex flex-wrap items-center gap-2">{experiments.length ? <><select aria-label="Completed experiment" className="w-full min-w-48 rounded-xl border border-white/[0.09] bg-[#07101f] px-3 py-2.5 text-sm text-slate-200 outline-none focus:border-cyan-300/30 sm:w-auto" value={selected} onChange={(event) => setSelected(event.target.value)}>{experiments.map((item) => <option key={item.experimentId} value={item.experimentId}>{item.name}</option>)}</select><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl border border-white/[0.09] bg-white/[0.035] px-3 py-2.5 text-sm text-slate-200 transition hover:border-cyan-200/20 hover:text-white"><Printer className="h-4 w-4" />Print</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-400 to-sky-500 px-3 py-2.5 text-sm font-semibold text-[#04101e] transition hover:brightness-110"><Download className="h-4 w-4" />CSV</button></> : <Badge>Demo workspace · reports</Badge>}</div></div>
    {state === "loading" ? <State title="Loading report" detail="Reading aggregate experiment results." /> : null}
    {state === "empty" ? <State title="No completed experiment data yet" detail="Complete an experiment to generate a baseline vs FairDrop report." href="/admin/experiments" action="Open experiments" /> : null}
    {state === "error" ? <State title="Unable to load report" detail="Try selecting another completed experiment or retry." /> : null}
    {state === "ready" && report ? <ReportView report={report} /> : null}
    <div className="flex items-center gap-2 px-1 text-xs leading-5 text-slate-600 print:hidden"><ArrowUpRight className="h-3.5 w-3.5" />Reports are produced from completed experiment runs in the demo workspace.</div>
  </div>;
}

function ReportView({ report }: { report: Report }) {
  const { summary } = report;
  return <><section className="rounded-2xl border border-white/[0.08] bg-[#07101f]/80 p-5 shadow-[0_20px_70px_rgba(2,8,23,0.2)] backdrop-blur-xl sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 font-mono text-[9px] uppercase tracking-[0.18em] text-cyan-300/70">Completed experiment</div><h2 className="text-xl font-semibold text-white">{summary.name}</h2></div><Badge>Measured run data</Badge></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-white/[0.06] pt-5 text-sm sm:grid-cols-4">{[["Scenario", summary.scenario], ["Virtual users", summary.virtualUsers], ["Duration", `${summary.durationSeconds} sec`], ["Request rate", `${summary.requestRate} req/s`], ["Concurrency", summary.concurrency], ["Seed", summary.seed], ["Baseline run", summary.baselineRunId], ["FairDrop run", summary.fairDropRunId]].map(([label, value]) => <Info key={String(label)} label={String(label)} value={String(value)} />)}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><Chart title="Latency comparison (ms)" values={report.charts.latency} /><Chart title="Allocation rate" values={report.charts.allocation} percentage /><Chart title="Integrity events" values={report.charts.integrity} /><Chart title="Request outcomes" values={report.charts.outcomes} /></section>
    <Metrics title="Performance" rows={[...rowsOf(report.performance.traffic), ...rowsOf(report.performance.latency), ...rowsOf(report.performance.responses), ...rowsOf(report.performance.errors)]} />
    <Metrics title="Queue" rows={rowsOf(report.queue)} /><Metrics title="Abuse & bot defense" rows={rowsOf(report.abuse)} /><Metrics title="Allocation" rows={rowsOf(report.allocation)} /><Metrics title="Integrity" rows={rowsOf(report.integrity)} />
    <section className="rounded-2xl border border-white/[0.08] bg-[#07101f]/80 p-5 shadow-[0_20px_70px_rgba(2,8,23,0.2)] backdrop-blur-xl sm:p-6"><div className="mb-4"><div className="font-mono text-[9px] uppercase tracking-[0.18em] text-cyan-300/70">Cohort comparison</div><h2 className="mt-1 font-semibold text-white">Fairness</h2></div><div className="grid gap-3 text-sm sm:grid-cols-2"><FairRate label="Baseline normal allocation" value={report.fairness.baselineNormalRate} /><FairRate label="Baseline attack allocation" value={report.fairness.baselineAttackRate} /><FairRate label="FairDrop normal allocation" value={report.fairness.fairDropNormalRate} /><FairRate label="FairDrop attack allocation" value={report.fairness.fairDropAttackRate} /><MetricLine label="Normal vs attack difference" value={report.fairness.normalVsAttackDifference} /></div></section>
  </>;
}
function reportRows(report: Report): [string, Compared][] { return [...rowsOf(report.performance.traffic), ...rowsOf(report.performance.latency), ...rowsOf(report.performance.responses), ...rowsOf(report.queue), ...rowsOf(report.abuse), ...rowsOf(report.allocation), ...rowsOf(report.integrity)]; }
function rowsOf(section: Record<string, Compared>): [string, Compared][] { return Object.entries(section).map(([key, value]) => [key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()), value]); }
function Metrics({ title, rows }: { title: string; rows: [string, Compared][] }) { return <section className="overflow-x-auto rounded-2xl border border-white/[0.08] bg-[#07101f]/80 p-5 shadow-[0_20px_70px_rgba(2,8,23,0.2)] backdrop-blur-xl sm:p-6"><div className="mb-3 font-mono text-[9px] uppercase tracking-[0.18em] text-cyan-300/70">Run metrics</div><h2 className="mb-3 font-semibold text-white">{title}</h2><table className="w-full min-w-[34rem] text-sm"><thead className="font-mono text-[9px] uppercase tracking-[0.12em] text-slate-500"><tr><th className="py-3 text-left font-medium">Metric</th><th className="text-center font-medium">Baseline</th><th className="text-center font-medium">FairDrop</th><th className="text-center font-medium">Difference</th></tr></thead><tbody>{rows.map(([label, value]) => <tr key={label} className="border-t border-white/[0.055]"><td className="py-2.5 text-slate-300">{label}</td><td className="text-center font-mono text-slate-400">{show(value.baseline)}</td><td className="text-center font-mono text-cyan-100">{show(value.fairDrop)}</td><td className="text-center font-mono text-slate-300">{show(value.difference)}</td></tr>)}</tbody></table></section>; }
function Chart({ title, values, percentage = false }: { title: string; values: Record<string, Compared>; percentage?: boolean }) { const maximum = percentage ? 1 : Math.max(1, ...Object.values(values).flatMap((value) => [value.baseline, value.fairDrop]).filter((value): value is number => typeof value === "number")); return <section className="rounded-2xl border border-white/[0.08] bg-[#07101f]/80 p-5 shadow-[0_20px_70px_rgba(2,8,23,0.2)] backdrop-blur-xl sm:p-6"><div className="mb-5"><div className="font-mono text-[9px] uppercase tracking-[0.18em] text-cyan-300/70">Comparison chart</div><h2 className="mt-1 font-semibold text-white">{title}</h2></div><div className="space-y-4">{Object.entries(values).map(([label, value]) => <div key={label}><div className="mb-2 flex justify-between gap-3 text-xs"><span className="truncate text-slate-400">{label}</span><span className="shrink-0 font-mono text-slate-300">{chartValue(value.baseline, percentage)} <span className="text-slate-600">/</span> <span className="text-cyan-100">{chartValue(value.fairDrop, percentage)}</span></span></div><div className="space-y-1.5"><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.045]"><div className="h-full rounded-full bg-slate-500/80" style={{ width: `${typeof value.baseline === "number" ? Math.min(100, Math.max(0, value.baseline) / maximum * 100) : 0}%` }} /></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.045]"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-blue-500" style={{ width: `${typeof value.fairDrop === "number" ? Math.min(100, Math.max(0, value.fairDrop) / maximum * 100) : 0}%` }} /></div></div></div>)}</div><p className="mt-5 font-mono text-[9px] uppercase tracking-[0.1em] text-slate-600">Gray: baseline <span className="mx-1">·</span> Cyan: FairDrop</p></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><div className="text-[9px] font-medium uppercase tracking-[0.12em] text-slate-500">{label}</div><div className="mt-1 break-all font-mono text-xs text-slate-200 sm:text-sm">{value}</div></div>; }
function FairRate({ label, value }: { label: string; value: { value: number | null; confidenceInterval95: { lower: number; upper: number } | null } }) { return <div className="rounded-xl border border-white/[0.06] bg-[#050b16]/65 p-3.5"><div className="text-slate-400">{label}</div><div className="mt-1 font-mono text-cyan-100">{value.value === null ? "N/A" : `${(value.value * 100).toFixed(2)}%`}</div><div className="mt-1 text-xs text-slate-600">{value.confidenceInterval95 ? `95% CI ${(value.confidenceInterval95.lower * 100).toFixed(1)}–${(value.confidenceInterval95.upper * 100).toFixed(1)}%` : "No confidence interval"}</div></div>; }
function MetricLine({ label, value }: { label: string; value: Compared }) { return <div className="rounded-xl border border-white/[0.06] bg-[#050b16]/65 p-3.5"><div className="text-slate-400">{label}</div><div className="mt-1 font-mono text-slate-200">Baseline {show(value.baseline)} <span className="text-slate-600">·</span> FairDrop {show(value.fairDrop)}</div></div>; }
function State({ title, detail, href, action }: { title: string; detail: string; href?: string; action?: string }) { return <section className="rounded-2xl border border-white/[0.08] bg-[#07101f]/80 p-8 text-center shadow-[0_20px_70px_rgba(2,8,23,0.2)]"><Badge>Demo workspace · reports</Badge><h2 className="mt-5 text-xl font-semibold text-white">{title}</h2><p className="mt-2 text-sm text-slate-400">{detail}</p>{href ? <Link href={href} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-400 to-sky-500 px-4 py-3 text-sm font-semibold text-[#04101e]">{action} <ArrowUpRight className="h-4 w-4" /></Link> : null}</section>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/15 bg-cyan-300/[0.055] px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.15em] text-cyan-100"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300" />{children}</span>; }
function chartValue(value: Value, percentage: boolean) { return percentage && typeof value === "number" ? `${(value * 100).toFixed(1)}%` : show(value); }
function show(value: Value) { return value === "NOT_APPLICABLE" ? "N/A" : Number.isFinite(value) ? value.toFixed(3) : "—"; }
