"use client";
import Script from "next/script";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, LockKeyhole } from "lucide-react";
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open(): void }; } }
export default function CheckoutPage() {
 const router=useRouter(); const [state,setState]=useState("Preparing a server-authorized Razorpay test order…"); const [ready,setReady]=useState(false); const [order,setOrder]=useState<{keyId:string;orderId:string;amount:number;currency:string;name:string}|null>(null);
 useEffect(()=>{ const allocationId=localStorage.getItem("fairdrop-live-demo-allocation"); if(!allocationId){queueMicrotask(()=>setState("No eligible allocation is available for checkout."));return;} void (async()=>{const r=await fetch("/api/payment/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({allocationId})});const d=await r.json();if(!r.ok){setState(d.error==="PAYMENT_NOT_CONFIGURED"?"Razorpay test keys are not configured on this environment.":d.error??"Unable to create the payment order.");return;}if(d.verified){router.push("/ticket");return;}setOrder(d);setState("Ready for Razorpay test checkout.");})()},[router]);
 async function pay(){if(!order||!window.Razorpay)return; setState("Opening Razorpay test checkout…"); const checkout=new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:order.name,order_id:order.orderId,handler:async(response:Record<string,string>)=>{setState("Verifying payment on the server…");const r=await fetch("/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(response)});const d=await r.json();if(r.ok&&d.verified){router.push("/ticket");}else setState(d.error??"Payment verification failed.");},modal:{ondismiss:()=>setState("Checkout closed. Your allocation remains unchanged.")}});checkout.open(); }
 return <main className="flex min-h-screen items-center justify-center bg-[#030611] px-4 pt-20 text-white"><Script src="https://checkout.razorpay.com/v1/checkout.js" onLoad={()=>setReady(true)}/><section className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#101a2d] p-8"><LockKeyhole className="h-8 w-8 text-violet-300"/><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-violet-300">Test mode only</p><h1 className="mt-2 text-3xl font-black">Secure checkout</h1><p className="mt-3 text-slate-400">₹499.00 · amount and allocation ownership are enforced server-side.</p><p role="status" className="mt-6 rounded-xl bg-black/20 p-4 text-sm text-slate-300">{!order&&state.includes("Preparing")?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:null}{state}</p><button disabled={!order||!ready} onClick={()=>void pay()} className="mt-5 w-full rounded-xl bg-violet-600 px-5 py-3 font-bold disabled:opacity-40">Pay ₹499 with Razorpay Test Mode</button></section></main>
}
