"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, CheckCircle2, Loader2, ShieldCheck, Ticket, Users } from "lucide-react";

type DemoRun = { simulationRunId: string; dropId: string; status: string; capacity: number | null; configuration: { virtualUsers: number; requestRate: number }; metrics: { activeVirtualUsers: number; completedVirtualUsers: number; totalRequests: number; requestsPerSecond: number; responses: { throttled429: number }; abuse: { blocked: number; duplicateAttempts: number; invalidTokenAttempts: number } } };
type Queue = { position: number; sequence: number; status: string };
const presets = [["last_seat_499", "Last-seat proof", "499 normal virtual users · you become #500"], ["sold_out_500", "Sold-out proof", "500 normal virtual users · you become #501"], ["quick_1k", "Mixed-attack demo", "1,000 virtual users · normal and attack profiles"], ["judge_5k", "Judge demo", "5,000 virtual users"], ["stress_50k", "Stress mode", "50,000 virtual users"]] as const;

export default function LiveDemoPage() {
  const router = useRouter(); const [run, setRun] = useState<DemoRun | null>(null); const [queue, setQueue] = useState<Queue | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("Choose a preset to start an isolated virtual crowd.");
  const refresh = useCallback(async (runId: string) => { const res = await fetch(`/api/demo/status?runId=${encodeURIComponent(runId)}`, { cache: "no-store" }); if (res.ok) setRun(await res.json()); }, []);
  useEffect(() => { const id = localStorage.getItem("fairdrop-live-demo-run"); if (id) void Promise.resolve().then(() => refresh(id)); }, [refresh]);
  useEffect(() => { if (!run || !["STARTING", "RUNNING", "STOPPING"].includes(run.status)) return; const timer = window.setInterval(() => void refresh(run.simulationRunId), 2000); return () => clearInterval(timer); }, [refresh, run]);
  async function start(preset: string) { setBusy(true); setMessage("Starting the isolated workload…"); try { const res = await fetch("/api/demo/start", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ preset }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error === "UNAUTHORIZED" ? "Sign in before starting the live demo." : data.message ?? "Could not start the demo."); localStorage.setItem("fairdrop-live-demo-run", data.simulationRunId); setRun({ ...data, capacity: 500, configuration: { virtualUsers: 0, requestRate: 0 }, metrics: { activeVirtualUsers: 0, completedVirtualUsers: 0, totalRequests: 0, requestsPerSecond: 0, responses: { throttled429: 0 }, abuse: { blocked: 0, duplicateAttempts: 0, invalidTokenAttempts: 0 } } }); await refresh(data.simulationRunId); setMessage("Virtual traffic is running. Join the same isolated drop when ready."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not start the demo."); } finally { setBusy(false); } }
  async function join() { if (!run) return; setBusy(true); try { const res = await fetch("/api/drop/join", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dropId: run.dropId }) }); if (!res.ok) throw new Error("Drop join was not accepted."); const q = await fetch("/api/queue/join", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dropId: run.dropId }) }); const data = await q.json(); if (!q.ok) throw new Error(data.error ?? "Queue entry was not accepted."); setQueue(data.queue); setMessage("You are in the real queue. Refreshing or retrying cannot improve your position."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not enter the queue."); } finally { setBusy(false); } }
  async function claim() { if (!run) return; setBusy(true); try { const res = await fetch("/api/allocation/claim", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dropId: run.dropId }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error === "NOT_ELIGIBLE" ? "Your real queue position is not eligible yet." : data.error ?? "Allocation was not accepted."); localStorage.setItem("fairdrop-live-demo-allocation", data.allocation.allocationId); router.push("/checkout"); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not claim a seat."); } finally { setBusy(false); } }
  const metrics = run?.metrics; const suspicious = (metrics?.abuse.duplicateAttempts ?? 0) + (metrics?.abuse.invalidTokenAttempts ?? 0);
  return <main className="min-h-screen bg-[#030611] px-4 pb-16 pt-28 text-white sm:px-6"><div className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">FairDrop · judge experience</p><h1 className="mt-2 text-4xl font-black">Live fair drop.</h1><p className="mt-3 max-w-3xl text-slate-400">A real authenticated participant enters an isolated, server-run virtual crowd. Queue order, abuse checks, allocation and payment are all decided by the production services.</p></header>
    <section className="grid gap-4 md:grid-cols-3">{presets.map(([id, title, detail]) => <button key={id} disabled={busy} onClick={() => void start(id)} className="rounded-2xl border border-white/10 bg-[#101a2d] p-5 text-left transition hover:border-violet-400/60 disabled:opacity-50"><Users className="h-5 w-5 text-violet-300"/><div className="mt-3 font-bold">{title}</div><div className="mt-1 text-sm text-slate-400">{detail}</div></button>)}</section>
    <p role="status" className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm text-slate-300">{busy ? <Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> : null}{message}</p>
    {run ? <><section className="rounded-2xl border border-violet-300/20 bg-[#101a2d] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Virtual crowd status</h2><p className="mt-1 text-sm text-slate-400">Run {run.simulationRunId}</p></div><span className="rounded-full bg-violet-500/15 px-3 py-1 text-xs font-bold text-violet-200">{run.status}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Configured", run.configuration.virtualUsers], ["Active", metrics?.activeVirtualUsers], ["Completed", metrics?.completedVirtualUsers], ["Actual RPS", metrics?.requestsPerSecond.toFixed(1)]].map(([label,value]) => <div key={String(label)} className="rounded-xl bg-black/25 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-mono text-lg">{value ?? "—"}</div></div>)}</div><div className="mt-4 text-sm text-slate-400">Requests: {metrics?.totalRequests ?? 0} · security signals: {suspicious} · throttled: {metrics?.responses.throttled429 ?? 0} · blocked: {metrics?.abuse.blocked ?? 0}</div>{run.status !== "COMPLETED" ? <p className="mt-4 text-sm font-medium text-amber-200">For exact last-seat and sold-out proofs, wait for this run to complete before joining.</p> : null}</section>
    <section className="rounded-2xl border border-white/10 bg-[#101a2d] p-6"><h2 className="flex items-center gap-2 text-xl font-bold"><ShieldCheck className="text-emerald-300"/>Your real queue entry</h2>{!queue ? <button disabled={busy} onClick={() => void join()} className="mt-4 rounded-xl bg-violet-600 px-5 py-3 font-bold hover:bg-violet-500 disabled:opacity-50">Join this live drop</button> : <div className="mt-4"><div className="text-5xl font-black text-violet-200">#{queue.position}</div><p className="mt-2 text-sm text-slate-400">Server sequence {queue.sequence}. Repeated requests do not change this number.</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={() => void claim()} className="rounded-xl bg-emerald-500 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">Claim seat if eligible</button><Link className="rounded-xl border border-white/15 px-5 py-3 font-bold" href="/ticket">View ticket</Link></div></div>}</section></> : null}
    <section className="grid gap-4 md:grid-cols-3 text-sm"><div className="rounded-xl border border-white/10 p-4"><Activity className="h-5 w-5 text-violet-300"/><b className="mt-2 block">Same core services</b><p className="mt-1 text-slate-400">Virtual and human actions use the protected drop, queue, abuse and allocation services.</p></div><div className="rounded-xl border border-white/10 p-4"><CheckCircle2 className="h-5 w-5 text-violet-300"/><b className="mt-2 block">No priority bypass</b><p className="mt-1 text-slate-400">Eligibility is calculated from the real server queue and 500-seat capacity.</p></div><div className="rounded-xl border border-white/10 p-4"><Ticket className="h-5 w-5 text-violet-300"/><b className="mt-2 block">Real checkout boundary</b><p className="mt-1 text-slate-400">Only a real allocation can create a Razorpay test order.</p></div></section>
  </div></main>;
}
