"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Loader2, RotateCcw, ShieldCheck } from "lucide-react";

type Preset = "last_seat" | "sold_out" | "bot_swarm" | "mixed_attack" | "normal_rush" | "custom";
type Draft = { capacity:number; preloadedAllocated:number; normalUsers:number; botUsers:number; duplicateUsers:number; tokenReplayUsers:number; requestFloodUsers:number; queueManipulationUsers:number; requestRate:number; maxConcurrency:number };
type Run = { simulationRunId:string; dropId:string; status:string; capacity:number; seatsAllocated:number; seatsRemaining:number; configuration:{virtualUsers:number;requestRate:number}; metrics:{activeVirtualUsers:number;completedVirtualUsers:number;totalRequests:number;requestsPerSecond:number;responses:{throttled429:number};abuse:{blocked:number;duplicateAttempts:number;invalidTokenAttempts:number};behaviorGroups:Record<string,{users:number;requests:number}>}; user:{participation:boolean;queue:{position:number;sequence:number;status:string}|null;allocation:{allocationId:string;seatId:string;status:string}|null} };
const presets: Record<Preset,{title:string;description:string;tests:string;draft:Draft}>={
 last_seat:{title:"Last Seat",description:"499 legitimate participants already hold seats. You are next in the real queue.",tests:"Final-seat allocation without overselling.",draft:{capacity:500,preloadedAllocated:499,normalUsers:2000,botUsers:0,duplicateUsers:0,tokenReplayUsers:0,requestFloodUsers:0,queueManipulationUsers:0,requestRate:500,maxConcurrency:200}},
 sold_out:{title:"Sold Out / You Are #501",description:"All 500 seats are already allocated before your real request arrives.",tests:"The allocation engine rejects seat #501.",draft:{capacity:500,preloadedAllocated:500,normalUsers:1000,botUsers:0,duplicateUsers:0,tokenReplayUsers:0,requestFloodUsers:0,queueManipulationUsers:0,requestRate:400,maxConcurrency:200}},
 bot_swarm:{title:"Bot Swarm",description:"Automated traffic competes with legitimate demand.",tests:"Abuse detection, throttling and blocking under bot pressure.",draft:{capacity:500,preloadedAllocated:0,normalUsers:500,botUsers:3000,duplicateUsers:500,tokenReplayUsers:250,requestFloodUsers:250,queueManipulationUsers:0,requestRate:1000,maxConcurrency:350}},
 mixed_attack:{title:"Mixed Attack",description:"Several attack profiles run alongside normal demand.",tests:"Duplicate, replay, flood and manipulation protections.",draft:{capacity:500,preloadedAllocated:0,normalUsers:1000,botUsers:0,duplicateUsers:1000,tokenReplayUsers:500,requestFloodUsers:1000,queueManipulationUsers:500,requestRate:1000,maxConcurrency:350}},
 normal_rush:{title:"Normal Rush",description:"Thousands of legitimate virtual users arrive together.",tests:"Fair queueing during high demand without attacks.",draft:{capacity:500,preloadedAllocated:0,normalUsers:5000,botUsers:0,duplicateUsers:0,tokenReplayUsers:0,requestFloodUsers:0,queueManipulationUsers:0,requestRate:1000,maxConcurrency:350}},
 custom:{title:"Custom Scenario",description:"Bounded isolated setup for a controlled judge demonstration.",tests:"Your selected safe configuration.",draft:{capacity:500,preloadedAllocated:0,normalUsers:500,botUsers:0,duplicateUsers:0,tokenReplayUsers:0,requestFloodUsers:0,queueManipulationUsers:0,requestRate:250,maxConcurrency:100}},
};
const fields: [keyof Draft,string][]=[["capacity","Total seats"],["preloadedAllocated","Already allocated"],["normalUsers","Normal users"],["botUsers","Bot users"],["duplicateUsers","Duplicate attackers"],["tokenReplayUsers","Token replay users"],["requestFloodUsers","Request-flood users"],["queueManipulationUsers","Queue-manipulation users"],["requestRate","Target RPS"],["maxConcurrency","Concurrency"]];

export default function LiveDemoPage(){
 const[selected,setSelected]=useState<Preset>("last_seat");const[draft,setDraft]=useState<Draft>(presets.last_seat.draft);const[run,setRun]=useState<Run|null>(null);const[message,setMessage]=useState("Choose a scenario, then start an isolated real workload.");const[busy,setBusy]=useState(false);
 const totalVirtual=useMemo(()=>draft.normalUsers+draft.botUsers+draft.duplicateUsers+draft.tokenReplayUsers+draft.requestFloodUsers+draft.queueManipulationUsers,[draft]);
 const refresh=useCallback(async(id:string)=>{const r=await fetch(`/api/demo/status?runId=${encodeURIComponent(id)}`,{cache:"no-store"});if(r.ok)setRun(await r.json())},[]);
 useEffect(()=>{const id=localStorage.getItem("fairdrop-live-demo-run");if(id)void Promise.resolve().then(()=>refresh(id))},[refresh]);
 useEffect(()=>{if(!run||!["STARTING","RUNNING","STOPPING"].includes(run.status))return;const timer=setInterval(()=>void refresh(run.simulationRunId),2000);return()=>clearInterval(timer)},[refresh,run]);
 function choose(preset:Preset){setSelected(preset);setDraft(presets[preset].draft);setMessage(presets[preset].description)}
 async function start(){if(draft.preloadedAllocated>draft.capacity){setMessage("Already allocated cannot exceed total seats.");return}if(draft.maxConcurrency>totalVirtual){setMessage("Concurrency cannot exceed virtual users.");return}setBusy(true);setMessage("Creating isolated drop and real preloaded scenario state…");try{const r=await fetch("/api/demo/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preset:selected,...draft})});const data=await r.json();if(!r.ok)throw new Error(data.message??data.error??"Scenario could not start.");localStorage.setItem("fairdrop-live-demo-run",data.simulationRunId);await refresh(data.simulationRunId);setMessage("Scenario ready. The preloaded state is real; join using your authenticated account.")}catch(e){setMessage(e instanceof Error?e.message:"Scenario could not start.")}finally{setBusy(false)}}
 async function join(){if(!run)return;setBusy(true);try{const a=await fetch("/api/drop/join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dropId:run.dropId})});if(!a.ok)throw new Error("Drop join was not accepted.");const q=await fetch("/api/queue/join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dropId:run.dropId})});if(!q.ok)throw new Error((await q.json()).error??"Queue entry was not accepted.");await refresh(run.simulationRunId);setMessage("Your queue position is server assigned and stable on refresh.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to join.")}finally{setBusy(false)}}
 async function claim(){if(!run)return;setBusy(true);try{const r=await fetch("/api/allocation/claim",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dropId:run.dropId})});const d=await r.json();await refresh(run.simulationRunId);if(!r.ok){setMessage(d.error==="NOT_ELIGIBLE"?"No seat is available for this real queue sequence. Overselling was prevented.":d.error??"Allocation denied.");return}localStorage.setItem("fairdrop-live-demo-allocation",d.allocation.allocationId);setMessage("Real allocation confirmed. Proceed to Razorpay test payment.")}catch{setMessage("Allocation is temporarily unavailable.")}finally{setBusy(false)}}
 async function reset(){if(!run)return;setBusy(true);try{const r=await fetch("/api/demo/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:run.simulationRunId})});if(!r.ok)throw new Error("Wait until the virtual workload completes before reset.");localStorage.removeItem("fairdrop-live-demo-run");setRun(null);setMessage("Isolated scenario resources were removed.")}catch(e){setMessage(e instanceof Error?e.message:"Reset failed.")}finally{setBusy(false)}}
 const metrics=run?.metrics;const signals=(metrics?.abuse.duplicateAttempts??0)+(metrics?.abuse.invalidTokenAttempts??0);const user=run?.user;const result=user?.allocation?"allocated":run&&user?.queue&&run.seatsRemaining===0?"soldout":"pending";
 return <main className="min-h-screen bg-[#030611] px-4 pb-16 pt-24 text-white sm:px-6"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">FairDrop Scenario Lab</p><h1 className="mt-2 text-4xl font-black">Choose the situation to prove.</h1><p className="mt-3 max-w-3xl text-slate-400">All virtual traffic is server-side. Your signed-in account still uses the real protected drop, queue, allocation and payment flow.</p></header>
 <section className="grid gap-3 md:grid-cols-3">{(Object.keys(presets) as Preset[]).map(id=><button key={id} onClick={()=>choose(id)} className={`rounded-2xl border p-4 text-left ${selected===id?"border-violet-400 bg-violet-500/10":"border-white/10 bg-[#101a2d]"}`}><b>{presets[id].title}</b><p className="mt-1 text-xs text-slate-400">{presets[id].description}</p></button>)}</section>
 <section className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl border border-white/10 bg-[#101a2d] p-5"><h2 className="font-bold">Scenario configuration</h2><p className="mt-1 text-sm text-slate-400">{presets[selected].tests}</p><div className="mt-4 grid grid-cols-2 gap-3">{fields.map(([key,label])=><label key={key} className={`text-xs text-slate-400 ${selected!=="custom"&&!["capacity","preloadedAllocated","requestRate","maxConcurrency"].includes(key)?"opacity-60":""}`}>{label}<input disabled={selected!=="custom"} type="number" min="0" value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white disabled:cursor-not-allowed"/></label>)}</div><div className="mt-4 rounded-lg bg-black/20 p-3 text-sm text-slate-300">Remaining seats: <b>{draft.capacity-draft.preloadedAllocated}</b> · Virtual workload: <b>{totalVirtual.toLocaleString()}</b></div><button disabled={busy} onClick={()=>void start()} className="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 font-bold disabled:opacity-50">{busy?<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>:null}Start scenario</button></div>
 <div className="rounded-2xl border border-violet-300/20 bg-[#101a2d] p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">Scenario status</h2><p className="mt-1 text-sm text-slate-400">{run?run.status:"Not started"}</p></div>{run?<button disabled={busy} onClick={()=>void reset()} className="text-xs text-slate-300"><RotateCcw className="mr-1 inline h-4 w-4"/>Reset scenario</button>:null}</div>{run?<><div className="mt-5 h-4 overflow-hidden rounded-full bg-black/40"><div className="h-full bg-violet-500" style={{width:`${Math.min(100,(run.seatsAllocated/run.capacity)*100)}%`}}/></div><p className="mt-2 text-sm">Seats: <b>{run.seatsAllocated} / {run.capacity}</b> · Remaining: <b>{run.seatsRemaining}</b></p><div className="mt-4 grid grid-cols-3 gap-3 text-sm">{[["Active",metrics?.activeVirtualUsers],["Completed",metrics?.completedVirtualUsers],["Requests",metrics?.totalRequests],["Actual RPS",metrics?.requestsPerSecond.toFixed(1)],["Security signals",signals],["Throttled",metrics?.responses.throttled429],["Blocked",metrics?.abuse.blocked]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-black/20 p-3"><span className="text-xs text-slate-500">{label}</span><b className="mt-1 block font-mono">{value??"—"}</b></div>)}</div></>:<p className="mt-8 text-slate-500">Start a preset to see aggregate backend metrics.</p>}</div></section>
 <p role="status" className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm text-slate-300">{message}</p>
 {run?<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#101a2d] p-5"><h2 className="flex items-center gap-2 font-bold"><ShieldCheck className="text-emerald-300"/>Your real status</h2><div className="mt-4 space-y-2 text-sm text-slate-300"><p>Authenticated: <b className="text-emerald-300">✓</b></p><p>Participation: <b>{user?.participation?"✓":"Pending"}</b></p><p>Queue: <b>{user?.queue?`#${user.queue.position} · ${user.queue.status}`:"Not joined"}</b></p><p>People ahead: <b>{user?.queue?Math.max(0,user.queue.position-1):"—"}</b></p><p>Allocation: <b>{user?.allocation?`Seat ${user.allocation.seatId}`:"Pending"}</b></p></div>{!user?.queue?<button disabled={busy} onClick={()=>void join()} className="mt-5 rounded-xl bg-violet-600 px-4 py-3 font-bold">Join real queue</button>:!user.allocation?<button disabled={busy} onClick={()=>void claim()} className="mt-5 rounded-xl bg-emerald-400 px-4 py-3 font-bold text-slate-950">Claim seat if eligible</button>:<Link href="/checkout" className="mt-5 inline-block rounded-xl bg-emerald-400 px-4 py-3 font-bold text-slate-950">Proceed to payment</Link>}</div>
 <div className={`rounded-2xl border p-5 ${result==="allocated"?"border-emerald-300/30 bg-emerald-400/[.06]":result==="soldout"?"border-amber-300/30 bg-amber-400/[.06]":"border-white/10 bg-[#101a2d]"}`}>{result==="allocated"?<><CheckCircle2 className="h-7 w-7 text-emerald-300"/><h2 className="mt-3 text-xl font-black">You got a real seat</h2><p className="mt-2 text-sm text-slate-300">Seat {user?.allocation?.seatId} was created by the atomic allocation engine. Payment is now available.</p></>:result==="soldout"?<><AlertTriangle className="h-7 w-7 text-amber-200"/><h2 className="mt-3 text-xl font-black">Drop sold out</h2><p className="mt-2 text-sm text-slate-300">{run.seatsAllocated} / {run.capacity} seats are allocated. Your request was processed correctly; FairDrop prevented overselling. No payment is offered.</p></>:<><Activity className="h-7 w-7 text-violet-300"/><h2 className="mt-3 text-xl font-black">Awaiting real result</h2><p className="mt-2 text-sm text-slate-400">The result card updates only after the protected backend processes your queue and allocation.</p></>}</div></section>:null}
 </div></main>
}
